language: node_js
node_js:
  - 'stable'
notifications:
  email: false
cache: yarn
jobs:
  include:
    - stage: "Lint"
      name: "Lint"
      script: cd theme && yarn lint && yarn type-check
    - stage: "Accessibility"
      name: "Accessibility"
      script: cd demo && yarn build && yarn a11y-static-report --folder=public
